#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 18 16:14:49 2017

@author: longjiemin
"""

class Solution(object):
    def maxArea(self, height):
        """
        :type height: List[int]
        :rtype: int
        """
        max_value = 0
        for i in range(len(height)-1):
            for j in range(i+1,len(height)):
                area = (min(height[i],height[j])*(j-i))
                max_value = max(max_value,area)
        return max_value
    
s = Solution()
